name: Docker

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        name: Build
        steps:

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: ghcr.io/${{ github.repository }}
                    tags: |
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}

            -   name: Build and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    platforms: linux/amd64,linux/arm64
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}

            -   name: Check Out Repo
                uses: actions/checkout@v2

            -   run: docker build ./. -t ${{ github.repository }}.slim:latest
            -   run: curl -L -O https://downloads.dockerslim.com/releases/1.37.3/dist_linux.tar.gz
            -   run: tar -zxvf dist_linux.tar.gz
            -   run: script -q -c "./dist_linux/docker-slim --debug version"
            -   run: script -q -c "./dist_linux/docker-slim build --target ${{ github.repository }}.slim:latest --show-blogs --http-probe=false --continue-after=10 --tag ghcr.io/${{ github.repository }}.slim:latest"

            -   name: Login to Github Packages
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Push
                run: |
                    docker push ghcr.io/${{ github.repository }}.slim:latest


